CREATE TABLE USER (
	IDX INT AUTO_INCREMENT PRIMARY KEY,
	Created BIGINT,
	UserId VARCHAR(10) NOT NULL,
	UserPw VARCHAR(32) NOT NULL,
	UserName VARCHAR(5) NOT NULL,
	SUBJECT INT,
	GRADE INT,
	CLASS INT,
	NUM INT
);

CREATE TABLE BUSBOARD (
  	Id 	INT AUTO_INCREMENT PRIMARY KEY,
  	Created BIGINT,
  	Writer VARCHAR(10) NOT NULL,
  	Title  VARCHAR(20),
  	Content VARCHAR(50)
);

CREATE TABLE PROFILE (
);

CREATE TABLE PORTFOLIO (
);

CREATE TABLE AWARD(
);

CREATE TABLE ENDBUSBOARD (
);